ALTER TABLE accounts
  ADD COLUMN IF NOT EXISTS meta_report_ghl_data_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE meta_report_months
  ADD COLUMN IF NOT EXISTS topline_source TEXT,
  ADD COLUMN IF NOT EXISTS manual_override BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS ghl_leads INTEGER,
  ADD COLUMN IF NOT EXISTS ghl_won_leads INTEGER,
  ADD COLUMN IF NOT EXISTS ghl_total_revenue NUMERIC,
  ADD COLUMN IF NOT EXISTS ghl_total_profit NUMERIC,
  ADD COLUMN IF NOT EXISTS ghl_synced_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS manual_leads INTEGER;
