ALTER TABLE google_ads_report_clients
  ADD COLUMN IF NOT EXISTS excel_sheet_url TEXT,
  ADD COLUMN IF NOT EXISTS spend_chart_type TEXT NOT NULL DEFAULT 'area',
  ADD COLUMN IF NOT EXISTS scenario_month_window TEXT NOT NULL DEFAULT '6',
  ADD COLUMN IF NOT EXISTS scenario_smooth_uneven BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS scenario_blend_history BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS scenario_include_trend BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS budget_multiplier NUMERIC NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS budget_baseline TEXT NOT NULL DEFAULT 'year';
